### ISSUE TITLE
[mediaqueries-4 ] Deprecate 'speech' media type as well?

### ISSUE THREAD

**Issue by plehegar** [w3c/a11y-review#18]
**This is a tracker issue.** Only discuss things here if they are a11y group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/1751

**Comment by michael-n-cooper** [comment]
Not sure in APA call where things stand on this or which disposition we prefer.

**Comment by michael-n-cooper** [comment]
APA agrees with deprecating.
