### ISSUE TITLE
[mediaqueries-5] high-contrast media feature

### ISSUE THREAD

**Issue by plehegar** [w3c/a11y-review#19]
**This is a tracker issue.** Only discuss things here if they are a11y group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/1286

**Comment by michael-n-cooper** [comment]
Media Queries 5 has [prefers-reduced-contrast](https://www.w3.org/TR/mediaqueries-5/#prefers-contrast) which *might* meet the requirements of this issue, in which case we don't need to track. But not sure yet.
