### ISSUE TITLE
[css-highlight-api] How should highlight pseudos be exposed to assistive techonologies?

### ISSUE THREAD

**Issue by plehegar** [w3c/a11y-review#2]
**This is a tracker issue.** Only discuss things here if they are a11y group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4601

**Comment by michael-n-cooper** [comment]
Closing as a dup, put a11y-tracker label on the dup.
