### ISSUE TITLE
[css-color-adjust-1][mediaqueries-5] Fold `forced-colors` and `prefers-contrast`?

### ISSUE THREAD

**Issue by plehegar** [w3c/a11y-review#3]
**This is a tracker issue.** Only discuss things here if they are a11y group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/3856

**Comment by michael-n-cooper** [comment]
Could be good to engage Andrew Somers.

**Comment by michael-n-cooper** [comment]
Awaiting return from vacation of James to sign off

**Comment by michael-n-cooper** [comment]
Closing in favor of #36.
