### ISSUE TITLE
[css-text] Add new CSS text-transform values for math

### ISSUE THREAD

**Issue by plehegar** [w3c/a11y-review#8]
**This is a tracker issue.** Only discuss things here if they are a11y group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/3745

**Comment by michael-n-cooper** [comment]
Issue was closed in favor of https://github.com/w3c/csswg-drafts/issues/5386; closing but starting tracking of the new one.
